% luminanceLevels = [0.2:0.4/9:0.6]
% 
% luminanceLevels =
% 
%     0.2000    0.2444    0.2889    0.3333    0.3778    0.4222    0.4667    0.5111    0.5556    0.6000

RunToyVirtualWorldRecipes('luminanceLevels',[0.2 0.6],...
    'reflectanceNumbers',[1 2],...
    'otherObjectReflectanceRandom',true,...
    'illuminantSpectraRandom',true,...
    'illuminantSpectrumNotFlat',true,...
    'targetSpectrumNotFlat',true,...
    'outputName','test',...
    'lightPositionRandom',false,'lightScaleRandom',false,'targetPositionRandom',false,...
    'targetScaleRandom',false,'shapeSet',{'BigBall'},'baseSceneSet',{'Library'},...
    'executeWidth',320,'executeHeight',240,'analyzeWidth',320,...
    'analyzeHeight',240,'analyzeCropImageHalfSize',25);


%%

ConeResponseToyVirtualWorldRecipes(...
        'outputName','NonFlatTargetFixedFlatIll',...
        'luminanceLevels', [0.2:0.4/9:0.6], ...
        'reflectanceNumbers', [1:10], ...
        'nAnnularRegions', 25, ...
        'mosaicHalfSize', 25);

%%

% Case 1: FlatFixedTargetIlluminantFixedBkGnd