%%testMakeMultispectralStruct test script to run MakeMultispectralStruct
tic;
MakeMultispectralStruct(...
    'folderName','StimuliRandomTargetShapeFixedIlluminantFixedBkGnd',...
    'luminanceLevels', linspace(0.2,0.6,10), ...
    'reflectanceNumbers', (1:100), ...
    'targetShape', 'BigBall', ...
    'baseScene', 'Library');
toc