function run1000scenes()
RunToyVirtualWorldRecipes('outputName','Set2Images1000Rotations10',...
    'imageWidth',320,...
    'imageHeight',240,...
    'cropImageHalfSize', 25, ...
    'nOtherObjectSurfaceReflectance', 999, ... % Number of random surfaces to choose from
    'luminanceLevels',(0.2:0.4/9:0.6),... 
    'reflectanceNumbers',(1:100),...
    'nInsertedLights', 1, ...
    'nInsertObjects', 0, ... % These are objects other than target objects
    'otherObjectReflectanceRandom',true,...
    'illuminantSpectraRandom',true,...
    'illuminantSpectrumNotFlat',true,...
    'targetSpectrumNotFlat',true,...    
    'lightPositionRandom',false,...
    'lightScaleRandom',false,...
    'targetPositionRandom',false,...
    'targetScaleRandom',false,...
    'shapeSet',{'BigBall'},...
    'baseSceneSet',{'Library'},...    
    'analyzeCropImageHalfSize',25,...
    'mosaicHalfSize', 25, ...
    'nRandomRotations', 10);