function Run1000TestScenes
%Run1000TestScenes
%
% Usage: 
%     Run100TestScenes
%
% Description:
%     Use the VWCC environment to generate 1000 test scenes according to parameters 
%     that Vijay Singh knows but didn't take the time to write down here.
%
% Input:
%    None
%
% Output:
%    The scene and image data is written into the output directory.
%
% Optional key/value pairs
%    None

% 07/08/17  dhb  Added a header comment, as far as I could.
%           dhb  Change name to match conventions of this project.

RunToyVirtualWorldRecipes('outputName','Set2Images1000Rotations10',...
    'imageWidth',320,...
    'imageHeight',240,...
    'cropImageHalfSize', 25, ...
    'nOtherObjectSurfaceReflectance', 999, ... % Number of random surfaces to choose from
    'luminanceLevels',(0.2:0.4/9:0.6),... 
    'reflectanceNumbers',(1:100),...
    'nInsertedLights', 1, ...
    'nInsertObjects', 0, ... % These are objects other than target objects
    'otherObjectReflectanceRandom',true,...
    'illuminantSpectraRandom',true,...
    'illuminantSpectrumNotFlat',true,...
    'targetSpectrumNotFlat',true,...    
    'lightPositionRandom',false,...
    'lightScaleRandom',false,...
    'targetPositionRandom',false,...
    'targetScaleRandom',false,...
    'shapeSet',{'BigBall'},...
    'baseSceneSet',{'Library'},...    
    'mosaicHalfSize', 25, ...
    'nRandomRotations', 10);